version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - .:/app
    ports:
      - "5432:5432"
  web:
    image: price-time-machine-app:1.0.0-ruby-3.0.2
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./tmp/bundle:/bundle
      - ./tmp/logs:/logs
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
      BUNDLE_PATH: "/bundle/vendor/ruby-2-6-8"
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    tty: true
    stdin_open: true
  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data
